basic:
    name: 'SFCC Product Landing Pages'
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - 'https://www.kj.com'
        - 'https://www.stonestreetwines.com'
        - 'https://www.lacrema.com'
        - 'https://www.siduri.com'
        - 'https://www.murphygoodewinery.com'
        - 'https://www.arrowoodwinery.com'
        - 'https://www.copainwines.com'
        - 'https://www.edmeades.com'
        - 'https://www.granmoraine.com'
        - 'https://www.pennerash.com'
        - 'https://www.willakenzie.com'
        - 'https://www.zenacorwnwines.com'
        - 'https://www.yourwinestore.com'
    monitoring:
        days: {  }
        type: daily
        schedule_time: '06:30 AM'
        schedule_time_zone: America/Phoenix
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 5
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
