basic:
    name: 'SFCC Product Landing Pages'
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - 'https://www.kj.com'
        - 'https://www.lacrema.com'
        - 'https://www.siduri.com'
        - 'https://www.murphygoodewinery.com'
        - 'https://www.arrowoodwinery.com'
        - 'https://www.copainwines.com'
        - 'https://www.edmeades.com'
        - 'https://www.granmoraine.com'
        - 'https://www.pennerash.com'
        - 'https://www.willakenzie.com'
        - 'https://www.zenacorwnwines.com'
        - 'https://www.yourwinestore.com'
        - 'https://www.copainwines.com/cpw-our-wines/'
        - 'https://www.copainwines.com/cpw-gift-shop/'
        - 'https://www.stonestreetwines.com/wines/'
        - 'https://www.stonestreetwines.com/wines-featured-wines/'
        - 'https://www.stonestreetwines.com/wines-featured-wines-upper-barn-chardonnay/'
        - 'https://www.stonestreetwines.com/wines-featured-wines-gravel-bench-chardonnay/'
        - 'https://www.stonestreetwines.com/wines-featured-wines-rockfall-vineyard-cabernet-sauvignon/'
        - 'https://www.stonestreetwines.com/wines-featured-wines-christophers-vineyard-cabernet-sauvignon/'
        - 'https://www.stonestreetwines.com/wines-white-wines/'
        - 'https://www.stonestreetwines.com/wines-white-wines-chardonnay/'
        - 'https://www.stonestreetwines.com/wines-white-wines-sauvignon-blanc/'
        - 'https://www.stonestreetwines.com/wines-white-wines-sparkling/'
        - 'https://www.stonestreetwines.com/wines-white-wines-interesting-whites/'
        - 'https://www.stonestreetwines.com/wines-red-wines/'
        - 'https://www.stonestreetwines.com/wines-red-wines-cabernet-sauvignon/'
        - 'https://www.stonestreetwines.com/wines-red-wines-red-blends/'
        - 'https://www.stonestreetwines.com/wines-library-list/'
        - 'https://www.murphygoodewinery.com/mgw-wine/'
        - 'https://www.arrowoodwinery.com/awd-wines/'
        - 'https://www.arrowoodwinery.com/awd-red-wines/'
        - 'https://www.arrowoodwinery.com/awd-white-wines/'
        - 'https://www.arrowoodwinery.com/awd-gift-packs/'
        - 'https://www.arrowoodwinery.com/awd-large-format/'
        - 'https://www.granmoraine.com/wines/'
        - 'https://www.pennerash.com/wines/'
        - 'https://www.pennerash.com/shop-wines-featured/'
        - 'https://www.pennerash.com/shop-wines-large-format-1/'
        - 'https://www.pennerash.com/shop-wines-library-wines/'
        - 'https://www.pennerash.com/shop-wines-pas-de-nom/'
        - 'https://www.pennerash.com/shop-wines-pinot-noir/'
        - 'https://www.pennerash.com/shop-wines-white-rose/'
        - 'https://www.willakenzie.com/our-wines'
        - 'https://www.willakenzie.com/our-wines-la-crete'
        - 'https://www.willakenzie.com/our-wines-single-vineyard'
        - 'https://www.willakenzie.com/our-wines-estate'
        - 'https://www.willakenzie.com/our-wines-willamette-valley'
        - 'https://www.willakenzie.com/our-wines-large-format-bottles'
        - 'https://www.zenacrown.com/wine/'
        - 'https://www.yourwinestore.com/yws-shop-wine-red-wine/'
        - 'https://www.yourwinestore.com/yws-shop-wine-red-wine-cabernet-sauvignon/'
        - 'https://www.yourwinestore.com/yws-shop-wine-red-wine-merlot/'
        - 'https://www.yourwinestore.com/yws-shop-wine-red-wine-pinot-noir/'
        - 'https://www.yourwinestore.com/yws-shop-wine-red-wine-zinfandel/'
        - 'https://www.yourwinestore.com/yws-shop-wine-red-wine-other-red-wine/'
        - 'https://www.yourwinestore.com/yws-shop-wine-white-wine/'
        - 'https://www.yourwinestore.com/yws-shop-wine-white-wine-chardonnay/'
        - 'https://www.yourwinestore.com/yws-shop-wine-white-wine-riesling/'
        - 'https://www.yourwinestore.com/yws-shop-wine-white-wine-sauvignon-blanc/'
        - 'https://www.yourwinestore.com/yws-shop-wine-white-wine-viognier/'
        - 'https://www.yourwinestore.com/yws-shop-wine-white-wine-other-white-wine/'
        - 'https://www.yourwinestore.com/yws-shop-wine-sparkling/'
        - 'https://www.yourwinestore.com/yws-shop-wine-sparkling-rose/'
        - 'https://www.yourwinestore.com/yws-shop-wine-sparkling-prosecco/'
        - 'https://www.yourwinestore.com/yws-shop-wine-champagne/'
        - 'https://www.yourwinestore.com/yws-shop-wine-sparkling-blanc-de-blancs/'
        - 'https://www.yourwinestore.com/yws-shop-wine-rose/'
        - 'https://www.yourwinestore.com/yws-shop-wine-rose-rose-of-pinot-noir/'
        - 'https://www.yourwinestore.com/yws-shop-wine-rose-of-sangiovese/'
        - 'https://www.yourwinestore.com/yws-shop-wine-featured/'
        - 'https://www.yourwinestore.com/yws-shop-wine-featured-best-sellers/'
        - 'https://www.yourwinestore.com/yws-shop-wine-featured-new-arrivals/'
        - 'https://www.yourwinestore.com/yws-shop-wine-featured-rated-90-plus-points/'
        - 'https://www.yourwinestore.com/yws-shop-wine-featured-cellar-collections/'
        - 'https://www.yourwinestore.com/yws-shop-wineries-all-featured.html'
    monitoring:
        days: {  }
        type: daily
        schedule_time: '06:30 AM'
        schedule_time_zone: America/Phoenix
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    sensitivity: 5
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
